"""workflow aprovacao e snapshots

Revision ID: 48fa5181d7bf
Revises: e93f311e952b
Create Date: 2026-09-29 16:50:14.981742

"""
from datetime import date, datetime, timedelta

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48fa5181d7bf'
down_revision = 'e93f311e952b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orcamento_historico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('status_de', sa.String(length=30), nullable=False),
    sa.Column('status_para', sa.String(length=30), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orcamento_historico', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orcamento_historico_orcamento_id'), ['orcamento_id'], unique=False)

    with op.batch_alter_table('orcamento_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snapshot_nome_produto', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('snapshot_fornecedor_nome', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('snapshot_preco_unit', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('snapshot_frete', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('snapshot_link', sa.String(length=500), nullable=True))

    connection = op.get_bind()
    itens_enviados = connection.execute(sa.text("""
        SELECT item.id, cot.nome_produto, fornecedor.nome, cot.preco,
               cot.frete, cot.link
        FROM orcamento_itens AS item
        JOIN orcamentos AS orcamento ON orcamento.id = item.orcamento_id
        JOIN cotacoes AS cot ON cot.id = item.cotacao_escolhida_id
        JOIN fornecedores AS fornecedor ON fornecedor.id = cot.fornecedor_id
        WHERE orcamento.status <> 'rascunho'
    """)).mappings().all()
    for item in itens_enviados:
        connection.execute(
            sa.text("""
                UPDATE orcamento_itens
                SET snapshot_nome_produto = :nome,
                    snapshot_fornecedor_nome = :fornecedor,
                    snapshot_preco_unit = :preco,
                    snapshot_frete = :frete,
                    snapshot_link = :link
                WHERE id = :id
            """),
            {
                "id": item["id"],
                "nome": item["nome_produto"],
                "fornecedor": item["nome"],
                "preco": item["preco"],
                "frete": item["frete"] or 0,
                "link": item["link"],
            },
        )

    orcamentos_sem_validade = connection.execute(sa.text("""
        SELECT id, criado_em FROM orcamentos
        WHERE status <> 'rascunho' AND validade IS NULL
    """)).mappings().all()
    for orcamento in orcamentos_sem_validade:
        criado_em = orcamento["criado_em"]
        if isinstance(criado_em, datetime):
            criado_em = criado_em.date()
        elif isinstance(criado_em, str):
            try:
                criado_em = datetime.fromisoformat(criado_em).date()
            except ValueError:
                criado_em = date.today()
        else:
            criado_em = date.today()
        connection.execute(
            sa.text("UPDATE orcamentos SET validade = :validade WHERE id = :id"),
            {"id": orcamento["id"], "validade": criado_em + timedelta(days=15)},
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamento_itens', schema=None) as batch_op:
        batch_op.drop_column('snapshot_link')
        batch_op.drop_column('snapshot_frete')
        batch_op.drop_column('snapshot_preco_unit')
        batch_op.drop_column('snapshot_fornecedor_nome')
        batch_op.drop_column('snapshot_nome_produto')

    with op.batch_alter_table('orcamento_historico', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamento_historico_orcamento_id'))

    op.drop_table('orcamento_historico')
    # ### end Alembic commands ###
