"""compartilhamento e email

Revision ID: 9c4ca14d49b2
Revises: 48fa5181d7bf
Create Date: 2026-09-29 17:19:02.710301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c4ca14d49b2'
down_revision = '48fa5181d7bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('envios_email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('destinatario', sa.String(length=254), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('envios_email', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_envios_email_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_envios_email_orcamento_id'), ['orcamento_id'], unique=False)

    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('share_expira_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('share_revogado', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.create_index(batch_op.f('ix_orcamentos_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orcamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orcamentos_share_token'))
        batch_op.drop_column('share_revogado')
        batch_op.drop_column('share_expira_em')
        batch_op.drop_column('share_token')

    with op.batch_alter_table('envios_email', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_envios_email_orcamento_id'))
        batch_op.drop_index(batch_op.f('ix_envios_email_criado_em'))

    op.drop_table('envios_email')
    # ### end Alembic commands ###
