"""initial schema

Revision ID: e93f311e952b
Revises:
Create Date: 2026-09-29 16:08:25.875636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e93f311e952b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=True),
    sa.Column('contato', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('produtos_busca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_pesquisado', sa.String(length=255), nullable=False),
    sa.Column('especificacoes', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos_busca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_busca_nome_pesquisado'), ['nome_pesquisado'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('cotacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_busca_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=255), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('imagem', sa.String(length=500), nullable=True),
    sa.Column('frete', sa.Float(), nullable=True),
    sa.Column('prazo_entrega', sa.String(length=80), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=120), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['produto_busca_id'], ['produtos_busca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotacoes_coletado_em'), ['coletado_em'], unique=False)

    op.create_table('orcamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=40), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('solicitante', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('condicoes_comerciais', sa.Text(), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('aprovacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('decisao', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('decidido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orcamento_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orcamento_id', sa.Integer(), nullable=False),
    sa.Column('produto_busca_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('cotacao_escolhida_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cotacao_escolhida_id'], ['cotacoes.id'], ),
    sa.ForeignKeyConstraint(['orcamento_id'], ['orcamentos.id'], ),
    sa.ForeignKeyConstraint(['produto_busca_id'], ['produtos_busca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orcamento_itens')
    op.drop_table('aprovacoes')
    op.drop_table('orcamentos')
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cotacoes_coletado_em'))

    op.drop_table('cotacoes')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('produtos_busca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_busca_nome_pesquisado'))

    op.drop_table('produtos_busca')
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
